/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "counter.v:1.1-14.10" *)
module counter(clk, rst, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.22-4.27" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "counter.v:3.11-3.14" *)
  input rst;
  wire rst;
  INV_X1 _13_ (
    .A(rst),
    .ZN(_04_)
  );
  AND3_X1 _14_ (
    .A1(count[2]),
    .A2(count[1]),
    .A3(count[0]),
    .ZN(_05_)
  );
  AOI21_X1 _15_ (
    .A(count[2]),
    .B1(count[1]),
    .B2(count[0]),
    .ZN(_06_)
  );
  NOR3_X1 _16_ (
    .A1(rst),
    .A2(_05_),
    .A3(_06_),
    .ZN(_00_)
  );
  OAI21_X1 _17_ (
    .A(_04_),
    .B1(count[0]),
    .B2(count[1]),
    .ZN(_07_)
  );
  AOI21_X1 _18_ (
    .A(_07_),
    .B1(count[0]),
    .B2(count[1]),
    .ZN(_01_)
  );
  NOR2_X1 _19_ (
    .A1(count[0]),
    .A2(rst),
    .ZN(_02_)
  );
  OAI21_X1 _20_ (
    .A(_04_),
    .B1(_05_),
    .B2(count[3]),
    .ZN(_08_)
  );
  AOI21_X1 _21_ (
    .A(_08_),
    .B1(_05_),
    .B2(count[3]),
    .ZN(_03_)
  );
  (* src = "counter.v:7.1-12.4" *)
  DFF_X1 _22_ (
    .CK(clk),
    .D(_02_),
    .Q(count[0]),
    .QN(_10_)
  );
  (* src = "counter.v:7.1-12.4" *)
  DFF_X1 _23_ (
    .CK(clk),
    .D(_01_),
    .Q(count[1]),
    .QN(_11_)
  );
  (* src = "counter.v:7.1-12.4" *)
  DFF_X1 _24_ (
    .CK(clk),
    .D(_00_),
    .Q(count[2]),
    .QN(_12_)
  );
  (* src = "counter.v:7.1-12.4" *)
  DFF_X1 _25_ (
    .CK(clk),
    .D(_03_),
    .Q(count[3]),
    .QN(_09_)
  );
endmodule
